import { Criteria } from '@samply/lens-core';

export const Lokalisation: Criteria = new Criteria(
  'urn:oid:2.16.840.1.113883.6.43.1',
  {
    de: 'Lokalization (ICD-O-3 classification)',
    en: 'Localization (ICD-O-3 classification)',
  },
  'string',
  'http://terminology.hl7.org/CodeSystem/icd-o-3',
  ['EQUALS'],
  [
      {
        key: "C00",
        en: "",
        de: "Malignant neoplasm of lip",
        display_short: "C00",
      },
      {
        key: "C00.0",
        en: "",
        de: "Malignant neoplasm: External upper lip",
        display_short: "C00.0",
      },
      {
        key: "C00.1",
        en: "",
        de: "Malignant neoplasm: External lower lip",
        display_short: "C00.1",
      },
      {
        key: "C00.2",
        en: "",
        de: "Malignant neoplasm: External lip, unspecified",
        display_short: "C00.2",
      },
      {
        key: "C00.3",
        en: "",
        de: "Malignant neoplasm: Upper lip, inner aspect",
        display_short: "C00.3",
      },
      {
        key: "C00.4",
        en: "",
        de: "Malignant neoplasm: Lower lip, inner aspect",
        display_short: "C00.4",
      },
      {
        key: "C00.5",
        en: "",
        de: "Malignant neoplasm: Lip, unspecified, inner aspect",
        display_short: "C00.5",
      },
      {
        key: "C00.6",
        en: "",
        de: "Malignant neoplasm: Commissure of lip",
        display_short: "C00.6",
      },
      {
        key: "C00.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of lip",
        display_short: "C00.8",
      },
      {
        key: "C00.9",
        en: "",
        de: "Malignant neoplasm: Lip, unspecified",
        display_short: "C00.9",
      },
      {
        key: "C01",
        en: "",
        de: "Malignant neoplasm of base of tongue",
        display_short: "C01",
      },
      {
        key: "C02",
        en: "",
        de: "Malignant neoplasm of other and unspecified parts of tongue",
        display_short: "C02",
      },
      {
        key: "C02.0",
        en: "",
        de: "Malignant neoplasm: Dorsal surface of tongue",
        display_short: "C02.0",
      },
      {
        key: "C02.1",
        en: "",
        de: "Malignant neoplasm: Border of tongue",
        display_short: "C02.1",
      },
      {
        key: "C02.2",
        en: "",
        de: "Malignant neoplasm: Ventral surface of tongue",
        display_short: "C02.2",
      },
      {
        key: "C02.3",
        en: "",
        de: "Malignant neoplasm: Anterior two-thirds of tongue, part unspecified",
        display_short: "C02.3",
      },
      {
        key: "C02.4",
        en: "",
        de: "Malignant neoplasm: Lingual tonsil",
        display_short: "C02.4",
      },
      {
        key: "C02.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of tongue",
        display_short: "C02.8",
      },
      {
        key: "C02.9",
        en: "",
        de: "Malignant neoplasm: Tongue, unspecified",
        display_short: "C02.9",
      },
      {
        key: "C03",
        en: "",
        de: "Malignant neoplasm of gum",
        display_short: "C03",
      },
      {
        key: "C03.0",
        en: "",
        de: "Malignant neoplasm: Upper gum",
        display_short: "C03.0",
      },
      {
        key: "C03.1",
        en: "",
        de: "Malignant neoplasm: Lower gum",
        display_short: "C03.1",
      },
      {
        key: "C03.9",
        en: "",
        de: "Malignant neoplasm: Gum, unspecified",
        display_short: "C03.9",
      },
      {
        key: "C04",
        en: "",
        de: "Malignant neoplasm of floor of mouth",
        display_short: "C04",
      },
      {
        key: "C04.0",
        en: "",
        de: "Malignant neoplasm: Anterior floor of mouth",
        display_short: "C04.0",
      },
      {
        key: "C04.1",
        en: "",
        de: "Malignant neoplasm: Lateral floor of mouth",
        display_short: "C04.1",
      },
      {
        key: "C04.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of floor of mouth",
        display_short: "C04.8",
      },
      {
        key: "C04.9",
        en: "",
        de: "Malignant neoplasm: Floor of mouth, unspecified",
        display_short: "C04.9",
      },
      {
        key: "C05",
        en: "",
        de: "Malignant neoplasm of palate",
        display_short: "C05",
      },
      {
        key: "C05.0",
        en: "",
        de: "Malignant neoplasm: Hard palate",
        display_short: "C05.0",
      },
      {
        key: "C05.1",
        en: "",
        de: "Malignant neoplasm: Soft palate",
        display_short: "C05.1",
      },
      {
        key: "C05.2",
        en: "",
        de: "Malignant neoplasm: Uvula",
        display_short: "C05.2",
      },
      {
        key: "C05.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of palate",
        display_short: "C05.8",
      },
      {
        key: "C05.9",
        en: "",
        de: "Malignant neoplasm: Palate, unspecified",
        display_short: "C05.9",
      },
      {
        key: "C06",
        en: "",
        de: "Malignant neoplasm of other and unspecified parts of mouth",
        display_short: "C06",
      },
      {
        key: "C06.0",
        en: "",
        de: "Malignant neoplasm: Cheek mucosa",
        display_short: "C06.0",
      },
      {
        key: "C06.1",
        en: "",
        de: "Malignant neoplasm: Vestibule of mouth",
        display_short: "C06.1",
      },
      {
        key: "C06.2",
        en: "",
        de: "Malignant neoplasm: Retromolar area",
        display_short: "C06.2",
      },
      {
        key: "C06.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of other and unspecified parts of mouth",
        display_short: "C06.8",
      },
      {
        key: "C06.9",
        en: "",
        de: "Malignant neoplasm: Mouth, unspecified",
        display_short: "C06.9",
      },
      {
        key: "C07",
        en: "",
        de: "Malignant neoplasm of parotid gland",
        display_short: "C07",
      },
      {
        key: "C08",
        en: "",
        de: "Malignant neoplasm of other and unspecified major salivary glands",
        display_short: "C08",
      },
      {
        key: "C08.0",
        en: "",
        de: "Malignant neoplasm: Submandibular gland",
        display_short: "C08.0",
      },
      {
        key: "C08.1",
        en: "",
        de: "Malignant neoplasm: Sublingual gland",
        display_short: "C08.1",
      },
      {
        key: "C08.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of major salivary glands",
        display_short: "C08.8",
      },
      {
        key: "C08.9",
        en: "",
        de: "Malignant neoplasm: Major salivary gland, unspecified",
        display_short: "C08.9",
      },
      {
        key: "C09",
        en: "",
        de: "Malignant neoplasm of tonsil",
        display_short: "C09",
      },
      {
        key: "C09.0",
        en: "",
        de: "Malignant neoplasm: Tonsillar fossa",
        display_short: "C09.0",
      },
      {
        key: "C09.1",
        en: "",
        de: "Malignant neoplasm: Tonsillar pillar (anterior)(posterior)",
        display_short: "C09.1",
      },
      {
        key: "C09.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of tonsil",
        display_short: "C09.8",
      },
      {
        key: "C09.9",
        en: "",
        de: "Malignant neoplasm: Tonsil, unspecified",
        display_short: "C09.9",
      },
      {
        key: "C10",
        en: "",
        de: "Malignant neoplasm of oropharynx",
        display_short: "C10",
      },
      {
        key: "C10.0",
        en: "",
        de: "Malignant neoplasm: Vallecula",
        display_short: "C10.0",
      },
      {
        key: "C10.1",
        en: "",
        de: "Malignant neoplasm: Anterior surface of epiglottis",
        display_short: "C10.1",
      },
      {
        key: "C10.2",
        en: "",
        de: "Malignant neoplasm: Lateral wall of oropharynx",
        display_short: "C10.2",
      },
      {
        key: "C10.3",
        en: "",
        de: "Malignant neoplasm: Posterior wall of oropharynx",
        display_short: "C10.3",
      },
      {
        key: "C10.4",
        en: "",
        de: "Malignant neoplasm: Branchial cleft",
        display_short: "C10.4",
      },
      {
        key: "C10.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of oropharynx",
        display_short: "C10.8",
      },
      {
        key: "C10.9",
        en: "",
        de: "Malignant neoplasm: Oropharynx, unspecified",
        display_short: "C10.9",
      },
      {
        key: "C11",
        en: "",
        de: "Malignant neoplasm of nasopharynx",
        display_short: "C11",
      },
      {
        key: "C11.0",
        en: "",
        de: "Malignant neoplasm: Superior wall of nasopharynx",
        display_short: "C11.0",
      },
      {
        key: "C11.1",
        en: "",
        de: "Malignant neoplasm: Posterior wall of nasopharynx",
        display_short: "C11.1",
      },
      {
        key: "C11.2",
        en: "",
        de: "Malignant neoplasm: Lateral wall of nasopharynx",
        display_short: "C11.2",
      },
      {
        key: "C11.3",
        en: "",
        de: "Malignant neoplasm: Anterior wall of nasopharynx",
        display_short: "C11.3",
      },
      {
        key: "C11.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of nasopharynx",
        display_short: "C11.8",
      },
      {
        key: "C11.9",
        en: "",
        de: "Malignant neoplasm: Nasopharynx, unspecified",
        display_short: "C11.9",
      },
      {
        key: "C12",
        en: "",
        de: "Malignant neoplasm of piriform sinus",
        display_short: "C12",
      },
      {
        key: "C13",
        en: "",
        de: "Malignant neoplasm of hypopharynx",
        display_short: "C13",
      },
      {
        key: "C13.0",
        en: "",
        de: "Malignant neoplasm: Postcricoid region",
        display_short: "C13.0",
      },
      {
        key: "C13.1",
        en: "",
        de: "Malignant neoplasm: Aryepiglottic fold, hypopharyngeal aspect",
        display_short: "C13.1",
      },
      {
        key: "C13.2",
        en: "",
        de: "Malignant neoplasm: Posterior wall of hypopharynx",
        display_short: "C13.2",
      },
      {
        key: "C13.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of hypopharynx",
        display_short: "C13.8",
      },
      {
        key: "C13.9",
        en: "",
        de: "Malignant neoplasm: Hypopharynx, unspecified",
        display_short: "C13.9",
      },
      {
        key: "C14",
        en: "",
        de: "Malignant neoplasm of other and ill-defined sites in the lip, oral cavity and pharynx",
        display_short: "C14",
      },
      {
        key: "C14.0",
        en: "",
        de: "Malignant neoplasm: Pharynx, unspecified",
        display_short: "C14.0",
      },
      {
        key: "C14.2",
        en: "",
        de: "Malignant neoplasm: Waldeyer ring",
        display_short: "C14.2",
      },
      {
        key: "C14.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of lip, oral cavity and pharynx",
        display_short: "C14.8",
      },
      {
        key: "C15",
        en: "",
        de: "Malignant neoplasm of oesophagus",
        display_short: "C15",
      },
      {
        key: "C15.0",
        en: "",
        de: "Malignant neoplasm: Cervical part of oesophagus",
        display_short: "C15.0",
      },
      {
        key: "C15.1",
        en: "",
        de: "Malignant neoplasm: Thoracic part of oesophagus",
        display_short: "C15.1",
      },
      {
        key: "C15.2",
        en: "",
        de: "Malignant neoplasm: Abdominal part of oesophagus",
        display_short: "C15.2",
      },
      {
        key: "C15.3",
        en: "",
        de: "Malignant neoplasm: Upper third of oesophagus",
        display_short: "C15.3",
      },
      {
        key: "C15.4",
        en: "",
        de: "Malignant neoplasm: Middle third of oesophagus",
        display_short: "C15.4",
      },
      {
        key: "C15.5",
        en: "",
        de: "Malignant neoplasm: Lower third of oesophagus",
        display_short: "C15.5",
      },
      {
        key: "C15.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of oesophagus",
        display_short: "C15.8",
      },
      {
        key: "C15.9",
        en: "",
        de: "Malignant neoplasm: Oesophagus, unspecified",
        display_short: "C15.9",
      },
      {
        key: "C16",
        en: "",
        de: "Malignant neoplasm of stomach",
        display_short: "C16",
      },
      {
        key: "C16.0",
        en: "",
        de: "Malignant neoplasm: Cardia",
        display_short: "C16.0",
      },
      {
        key: "C16.1",
        en: "",
        de: "Malignant neoplasm: Fundus of stomach",
        display_short: "C16.1",
      },
      {
        key: "C16.2",
        en: "",
        de: "Malignant neoplasm: Body of stomach",
        display_short: "C16.2",
      },
      {
        key: "C16.3",
        en: "",
        de: "Malignant neoplasm: Pyloric antrum",
        display_short: "C16.3",
      },
      {
        key: "C16.4",
        en: "",
        de: "Malignant neoplasm: Pylorus",
        display_short: "C16.4",
      },
      {
        key: "C16.5",
        en: "",
        de: "Malignant neoplasm: Lesser curvature of stomach, unspecified",
        display_short: "C16.5",
      },
      {
        key: "C16.6",
        en: "",
        de: "Malignant neoplasm: Greater curvature of stomach, unspecified",
        display_short: "C16.6",
      },
      {
        key: "C16.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of stomach",
        display_short: "C16.8",
      },
      {
        key: "C16.9",
        en: "",
        de: "Malignant neoplasm: Stomach, unspecified",
        display_short: "C16.9",
      },
      {
        key: "C17",
        en: "",
        de: "Malignant neoplasm of small intestine",
        display_short: "C17",
      },
      {
        key: "C17.0",
        en: "",
        de: "Malignant neoplasm: Duodenum",
        display_short: "C17.0",
      },
      {
        key: "C17.1",
        en: "",
        de: "Malignant neoplasm: Jejunum",
        display_short: "C17.1",
      },
      {
        key: "C17.2",
        en: "",
        de: "Malignant neoplasm: Ileum",
        display_short: "C17.2",
      },
      {
        key: "C17.3",
        en: "",
        de: "Malignant neoplasm: Meckel diverticulum",
        display_short: "C17.3",
      },
      {
        key: "C17.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of small intestine",
        display_short: "C17.8",
      },
      {
        key: "C17.9",
        en: "",
        de: "Malignant neoplasm: Small intestine, unspecified",
        display_short: "C17.9",
      },
      {
        key: "C18",
        en: "",
        de: "Malignant neoplasm of colon",
        display_short: "C18",
      },
      {
        key: "C18.0",
        en: "",
        de: "Malignant neoplasm: Caecum",
        display_short: "C18.0",
      },
      {
        key: "C18.1",
        en: "",
        de: "Malignant neoplasm: Appendix",
        display_short: "C18.1",
      },
      {
        key: "C18.2",
        en: "",
        de: "Malignant neoplasm: Ascending colon",
        display_short: "C18.2",
      },
      {
        key: "C18.3",
        en: "",
        de: "Malignant neoplasm: Hepatic flexure",
        display_short: "C18.3",
      },
      {
        key: "C18.4",
        en: "",
        de: "Malignant neoplasm: Transverse colon",
        display_short: "C18.4",
      },
      {
        key: "C18.5",
        en: "",
        de: "Malignant neoplasm: Splenic flexure",
        display_short: "C18.5",
      },
      {
        key: "C18.6",
        en: "",
        de: "Malignant neoplasm: Descending colon",
        display_short: "C18.6",
      },
      {
        key: "C18.7",
        en: "",
        de: "Malignant neoplasm: Sigmoid colon",
        display_short: "C18.7",
      },
      {
        key: "C18.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of colon",
        display_short: "C18.8",
      },
      {
        key: "C18.9",
        en: "",
        de: "Malignant neoplasm: Colon, unspecified",
        display_short: "C18.9",
      },
      {
        key: "C19",
        en: "",
        de: "Malignant neoplasm of rectosigmoid junction",
        display_short: "C19",
      },
      {
        key: "C20",
        en: "",
        de: "Malignant neoplasm of rectum",
        display_short: "C20",
      },
      {
        key: "C21",
        en: "",
        de: "Malignant neoplasm of anus and anal canal",
        display_short: "C21",
      },
      {
        key: "C21.0",
        en: "",
        de: "Malignant neoplasm: Anus, unspecified",
        display_short: "C21.0",
      },
      {
        key: "C21.1",
        en: "",
        de: "Malignant neoplasm: Anal canal",
        display_short: "C21.1",
      },
      {
        key: "C21.2",
        en: "",
        de: "Malignant neoplasm: Cloacogenic zone",
        display_short: "C21.2",
      },
      {
        key: "C21.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of rectum, anus and anal canal",
        display_short: "C21.8",
      },
      {
        key: "C22",
        en: "",
        de: "Malignant neoplasm of liver and intrahepatic bile ducts",
        display_short: "C22",
      },
      {
        key: "C22.0",
        en: "",
        de: "Malignant neoplasm: Liver cell carcinoma",
        display_short: "C22.0",
      },
      {
        key: "C22.1",
        en: "",
        de: "Malignant neoplasm: Intrahepatic bile duct carcinoma",
        display_short: "C22.1",
      },
      {
        key: "C22.2",
        en: "",
        de: "Malignant neoplasm: Hepatoblastoma",
        display_short: "C22.2",
      },
      {
        key: "C22.3",
        en: "",
        de: "Malignant neoplasm: Angiosarcoma of liver",
        display_short: "C22.3",
      },
      {
        key: "C22.4",
        en: "",
        de: "Malignant neoplasm: Other sarcomas of liver",
        display_short: "C22.4",
      },
      {
        key: "C22.7",
        en: "",
        de: "Malignant neoplasm: Other specified carcinomas of liver",
        display_short: "C22.7",
      },
      {
        key: "C22.9",
        en: "",
        de: "Malignant neoplasm: Liver, unspecified",
        display_short: "C22.9",
      },
      {
        key: "C23",
        en: "",
        de: "Malignant neoplasm of gallbladder",
        display_short: "C23",
      },
      {
        key: "C24",
        en: "",
        de: "Malignant neoplasm of other and unspecified parts of biliary tract",
        display_short: "C24",
      },
      {
        key: "C24.0",
        en: "",
        de: "Malignant neoplasm: Extrahepatic bile duct",
        display_short: "C24.0",
      },
      {
        key: "C24.1",
        en: "",
        de: "Malignant neoplasm: Ampulla of Vater",
        display_short: "C24.1",
      },
      {
        key: "C24.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of biliary tract",
        display_short: "C24.8",
      },
      {
        key: "C24.9",
        en: "",
        de: "Malignant neoplasm: Biliary tract, unspecified",
        display_short: "C24.9",
      },
      {
        key: "C25",
        en: "",
        de: "Malignant neoplasm of pancreas",
        display_short: "C25",
      },
      {
        key: "C25.0",
        en: "",
        de: "Malignant neoplasm: Head of pancreas",
        display_short: "C25.0",
      },
      {
        key: "C25.1",
        en: "",
        de: "Malignant neoplasm: Body of pancreas",
        display_short: "C25.1",
      },
      {
        key: "C25.2",
        en: "",
        de: "Malignant neoplasm: Tail of pancreas",
        display_short: "C25.2",
      },
      {
        key: "C25.3",
        en: "",
        de: "Malignant neoplasm: Pancreatic duct",
        display_short: "C25.3",
      },
      {
        key: "C25.4",
        en: "",
        de: "Malignant neoplasm: Endocrine pancreas",
        display_short: "C25.4",
      },
      {
        key: "C25.7",
        en: "",
        de: "Malignant neoplasm: Other parts of pancreas",
        display_short: "C25.7",
      },
      {
        key: "C25.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of pancreas",
        display_short: "C25.8",
      },
      {
        key: "C25.9",
        en: "",
        de: "Malignant neoplasm: Pancreas, unspecified",
        display_short: "C25.9",
      },
      {
        key: "C26",
        en: "",
        de: "Malignant neoplasm of other and ill-defined digestive organs",
        display_short: "C26",
      },
      {
        key: "C26.0",
        en: "",
        de: "Malignant neoplasm: Intestinal tract, part unspecified",
        display_short: "C26.0",
      },
      {
        key: "C26.1",
        en: "",
        de: "Malignant neoplasm: Spleen",
        display_short: "C26.1",
      },
      {
        key: "C26.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of digestive system",
        display_short: "C26.8",
      },
      {
        key: "C26.9",
        en: "",
        de: "Malignant neoplasm: Ill-defined sites within the digestive system",
        display_short: "C26.9",
      },
      {
        key: "C30",
        en: "",
        de: "Malignant neoplasm of nasal cavity and middle ear",
        display_short: "C30",
      },
      {
        key: "C30.0",
        en: "",
        de: "Malignant neoplasm: Nasal cavity",
        display_short: "C30.0",
      },
      {
        key: "C30.1",
        en: "",
        de: "Malignant neoplasm: Middle ear",
        display_short: "C30.1",
      },
      {
        key: "C31",
        en: "",
        de: "Malignant neoplasm of accessory sinuses",
        display_short: "C31",
      },
      {
        key: "C31.0",
        en: "",
        de: "Malignant neoplasm: Maxillary sinus",
        display_short: "C31.0",
      },
      {
        key: "C31.1",
        en: "",
        de: "Malignant neoplasm: Ethmoidal sinus",
        display_short: "C31.1",
      },
      {
        key: "C31.2",
        en: "",
        de: "Malignant neoplasm: Frontal sinus",
        display_short: "C31.2",
      },
      {
        key: "C31.3",
        en: "",
        de: "Malignant neoplasm: Sphenoidal sinus",
        display_short: "C31.3",
      },
      {
        key: "C31.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of accessory sinuses",
        display_short: "C31.8",
      },
      {
        key: "C31.9",
        en: "",
        de: "Malignant neoplasm: Accessory sinus, unspecified",
        display_short: "C31.9",
      },
      {
        key: "C32",
        en: "",
        de: "Malignant neoplasm of larynx",
        display_short: "C32",
      },
      {
        key: "C32.0",
        en: "",
        de: "Malignant neoplasm: Glottis",
        display_short: "C32.0",
      },
      {
        key: "C32.1",
        en: "",
        de: "Malignant neoplasm: Supraglottis",
        display_short: "C32.1",
      },
      {
        key: "C32.2",
        en: "",
        de: "Malignant neoplasm: Subglottis",
        display_short: "C32.2",
      },
      {
        key: "C32.3",
        en: "",
        de: "Malignant neoplasm: Laryngeal cartilage",
        display_short: "C32.3",
      },
      {
        key: "C32.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of larynx",
        display_short: "C32.8",
      },
      {
        key: "C32.9",
        en: "",
        de: "Malignant neoplasm: Larynx, unspecified",
        display_short: "C32.9",
      },
      {
        key: "C33",
        en: "",
        de: "Malignant neoplasm of trachea",
        display_short: "C33",
      },
      {
        key: "C34",
        en: "",
        de: "Malignant neoplasm of bronchus and lung",
        display_short: "C34",
      },
      {
        key: "C34.0",
        en: "",
        de: "Malignant neoplasm: Main bronchus",
        display_short: "C34.0",
      },
      {
        key: "C34.1",
        en: "",
        de: "Malignant neoplasm: Upper lobe, bronchus or lung",
        display_short: "C34.1",
      },
      {
        key: "C34.2",
        en: "",
        de: "Malignant neoplasm: Middle lobe, bronchus or lung",
        display_short: "C34.2",
      },
      {
        key: "C34.3",
        en: "",
        de: "Malignant neoplasm: Lower lobe, bronchus or lung",
        display_short: "C34.3",
      },
      {
        key: "C34.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of bronchus and lung",
        display_short: "C34.8",
      },
      {
        key: "C34.9",
        en: "",
        de: "Malignant neoplasm: Bronchus or lung, unspecified",
        display_short: "C34.9",
      },
      {
        key: "C37",
        en: "",
        de: "Malignant neoplasm of thymus",
        display_short: "C37",
      },
      {
        key: "C38",
        en: "",
        de: "Malignant neoplasm of heart, mediastinum and pleura",
        display_short: "C38",
      },
      {
        key: "C38.0",
        en: "",
        de: "Malignant neoplasm: Heart",
        display_short: "C38.0",
      },
      {
        key: "C38.1",
        en: "",
        de: "Malignant neoplasm: Anterior mediastinum",
        display_short: "C38.1",
      },
      {
        key: "C38.2",
        en: "",
        de: "Malignant neoplasm: Posterior mediastinum",
        display_short: "C38.2",
      },
      {
        key: "C38.3",
        en: "",
        de: "Malignant neoplasm: Mediastinum, part unspecified",
        display_short: "C38.3",
      },
      {
        key: "C38.4",
        en: "",
        de: "Malignant neoplasm: Pleura",
        display_short: "C38.4",
      },
      {
        key: "C38.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of heart, mediastinum and pleura",
        display_short: "C38.8",
      },
      {
        key: "C39",
        en: "",
        de: "Malignant neoplasm of other and ill-defined sites in the respiratory system and intrathoracic organs",
        display_short: "C39",
      },
      {
        key: "C39.0",
        en: "",
        de: "Malignant neoplasm: Upper respiratory tract, part unspecified",
        display_short: "C39.0",
      },
      {
        key: "C39.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of respiratory and intrathoracic organs",
        display_short: "C39.8",
      },
      {
        key: "C39.9",
        en: "",
        de: "Malignant neoplasm: Ill-defined sites within the respiratory system",
        display_short: "C39.9",
      },
      {
        key: "C40",
        en: "",
        de: "Malignant neoplasm of bone and articular cartilage of limbs",
        display_short: "C40",
      },
      {
        key: "C40.0",
        en: "",
        de: "Malignant neoplasm: Scapula and long bones of upper limb",
        display_short: "C40.0",
      },
      {
        key: "C40.1",
        en: "",
        de: "Malignant neoplasm: Short bones of upper limb",
        display_short: "C40.1",
      },
      {
        key: "C40.2",
        en: "",
        de: "Malignant neoplasm: Long bones of lower limb",
        display_short: "C40.2",
      },
      {
        key: "C40.3",
        en: "",
        de: "Malignant neoplasm: Short bones of lower limb",
        display_short: "C40.3",
      },
      {
        key: "C40.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of bone and articular cartilage of limbs",
        display_short: "C40.8",
      },
      {
        key: "C40.9",
        en: "",
        de: "Malignant neoplasm: Bone and articular cartilage of limb, unspecified",
        display_short: "C40.9",
      },
      {
        key: "C41",
        en: "",
        de: "Malignant neoplasm of bone and articular cartilage of other and unspecified sites",
        display_short: "C41",
      },
      {
        key: "C41.0",
        en: "",
        de: "Malignant neoplasm: Bones of skull and face",
        display_short: "C41.0",
      },
      {
        key: "C41.1",
        en: "",
        de: "Malignant neoplasm: Mandible",
        display_short: "C41.1",
      },
      {
        key: "C41.2",
        en: "",
        de: "Malignant neoplasm: Vertebral column",
        display_short: "C41.2",
      },
      {
        key: "C41.3",
        en: "",
        de: "Malignant neoplasm: Ribs, sternum and clavicle",
        display_short: "C41.3",
      },
      {
        key: "C41.4",
        en: "",
        de: "Malignant neoplasm: Pelvic bones, sacrum and coccyx",
        display_short: "C41.4",
      },
      {
        key: "C41.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of bone and articular cartilage",
        display_short: "C41.8",
      },
      {
        key: "C41.9",
        en: "",
        de: "Malignant neoplasm: Bone and articular cartilage, unspecified",
        display_short: "C41.9",
      },
      {
        key: "C43",
        en: "",
        de: "Malignant melanoma of skin",
        display_short: "C43",
      },
      {
        key: "C43.0",
        en: "",
        de: "Malignant neoplasm: Malignant melanoma of lip",
        display_short: "C43.0",
      },
      {
        key: "C43.1",
        en: "",
        de: "Malignant neoplasm: Malignant melanoma of eyelid, including canthus",
        display_short: "C43.1",
      },
      {
        key: "C43.2",
        en: "",
        de: "Malignant neoplasm: Malignant melanoma of ear and external auricular canal",
        display_short: "C43.2",
      },
      {
        key: "C43.3",
        en: "",
        de: "Malignant neoplasm: Malignant melanoma of other and unspecified parts of face",
        display_short: "C43.3",
      },
      {
        key: "C43.4",
        en: "",
        de: "Malignant neoplasm: Malignant melanoma of scalp and neck",
        display_short: "C43.4",
      },
      {
        key: "C43.5",
        en: "",
        de: "Malignant neoplasm: Malignant melanoma of trunk",
        display_short: "C43.5",
      },
      {
        key: "C43.6",
        en: "",
        de: "Malignant neoplasm: Malignant melanoma of upper limb, including shoulder",
        display_short: "C43.6",
      },
      {
        key: "C43.7",
        en: "",
        de: "Malignant neoplasm: Malignant melanoma of lower limb, including hip",
        display_short: "C43.7",
      },
      {
        key: "C43.8",
        en: "",
        de: "Malignant neoplasm: Overlapping malignant melanoma of skin",
        display_short: "C43.8",
      },
      {
        key: "C43.9",
        en: "",
        de: "Malignant neoplasm: Malignant melanoma of skin, unspecified",
        display_short: "C43.9",
      },
      {
        key: "C44",
        en: "",
        de: "Other malignant neoplasms of skin",
        display_short: "C44",
      },
      {
        key: "C44.0",
        en: "",
        de: "Malignant neoplasm: Skin of lip",
        display_short: "C44.0",
      },
      {
        key: "C44.1",
        en: "",
        de: "Malignant neoplasm: Skin of eyelid, including canthus",
        display_short: "C44.1",
      },
      {
        key: "C44.2",
        en: "",
        de: "Malignant neoplasm: Skin of ear and external auricular canal",
        display_short: "C44.2",
      },
      {
        key: "C44.3",
        en: "",
        de: "Malignant neoplasm: Skin of other and unspecified parts of face",
        display_short: "C44.3",
      },
      {
        key: "C44.4",
        en: "",
        de: "Malignant neoplasm: Skin of scalp and neck",
        display_short: "C44.4",
      },
      {
        key: "C44.5",
        en: "",
        de: "Malignant neoplasm: Skin of trunk",
        display_short: "C44.5",
      },
      {
        key: "C44.6",
        en: "",
        de: "Malignant neoplasm: Skin of upper limb, including shoulder",
        display_short: "C44.6",
      },
      {
        key: "C44.7",
        en: "",
        de: "Malignant neoplasm: Skin of lower limb, including hip",
        display_short: "C44.7",
      },
      {
        key: "C44.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of skin",
        display_short: "C44.8",
      },
      {
        key: "C44.9",
        en: "",
        de: "Malignant neoplasm: Malignant neoplasm of skin, unspecified",
        display_short: "C44.9",
      },
      {
        key: "C45",
        en: "",
        de: "Mesothelioma",
        display_short: "C45",
      },
      {
        key: "C45.0",
        en: "",
        de: "Mesothelioma of pleura",
        display_short: "C45.0",
      },
      {
        key: "C45.1",
        en: "",
        de: "Mesothelioma of peritoneum",
        display_short: "C45.1",
      },
      {
        key: "C45.2",
        en: "",
        de: "Mesothelioma of pericardium",
        display_short: "C45.2",
      },
      {
        key: "C45.7",
        en: "",
        de: "Mesothelioma of other sites",
        display_short: "C45.7",
      },
      {
        key: "C45.9",
        en: "",
        de: "Mesothelioma, unspecified",
        display_short: "C45.9",
      },
      {
        key: "C46",
        en: "",
        de: "Kaposi sarcoma",
        display_short: "C46",
      },
      {
        key: "C46.0",
        en: "",
        de: "Kaposi sarcoma of skin",
        display_short: "C46.0",
      },
      {
        key: "C46.1",
        en: "",
        de: "Kaposi sarcoma of soft tissue",
        display_short: "C46.1",
      },
      {
        key: "C46.2",
        en: "",
        de: "Kaposi sarcoma of palate",
        display_short: "C46.2",
      },
      {
        key: "C46.3",
        en: "",
        de: "Kaposi sarcoma of lymph nodes",
        display_short: "C46.3",
      },
      {
        key: "C46.7",
        en: "",
        de: "Kaposi sarcoma of other sites",
        display_short: "C46.7",
      },
      {
        key: "C46.8",
        en: "",
        de: "Kaposi sarcoma of multiple organs",
        display_short: "C46.8",
      },
      {
        key: "C46.9",
        en: "",
        de: "Kaposi sarcoma, unspecified",
        display_short: "C46.9",
      },
      {
        key: "C47",
        en: "",
        de: "Malignant neoplasm of peripheral nerves and autonomic nervous system",
        display_short: "C47",
      },
      {
        key: "C47.0",
        en: "",
        de: "Malignant neoplasm: Peripheral nerves of head, face and neck",
        display_short: "C47.0",
      },
      {
        key: "C47.1",
        en: "",
        de: "Malignant neoplasm: Peripheral nerves of upper limb, including shoulder",
        display_short: "C47.1",
      },
      {
        key: "C47.2",
        en: "",
        de: "Malignant neoplasm: Peripheral nerves of lower limb, including hip",
        display_short: "C47.2",
      },
      {
        key: "C47.3",
        en: "",
        de: "Malignant neoplasm: Peripheral nerves of thorax",
        display_short: "C47.3",
      },
      {
        key: "C47.4",
        en: "",
        de: "Malignant neoplasm: Peripheral nerves of abdomen",
        display_short: "C47.4",
      },
      {
        key: "C47.5",
        en: "",
        de: "Malignant neoplasm: Peripheral nerves of pelvis",
        display_short: "C47.5",
      },
      {
        key: "C47.6",
        en: "",
        de: "Malignant neoplasm: Peripheral nerves of trunk, unspecified",
        display_short: "C47.6",
      },
      {
        key: "C47.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of peripheral nerves and autonomic nervous system",
        display_short: "C47.8",
      },
      {
        key: "C47.9",
        en: "",
        de: "Malignant neoplasm: Peripheral nerves and autonomic nervous system, unspecified",
        display_short: "C47.9",
      },
      {
        key: "C48",
        en: "",
        de: "Malignant neoplasm of retroperitoneum and peritoneum",
        display_short: "C48",
      },
      {
        key: "C48.0",
        en: "",
        de: "Malignant neoplasm: Retroperitoneum",
        display_short: "C48.0",
      },
      {
        key: "C48.1",
        en: "",
        de: "Malignant neoplasm: Specified parts of peritoneum",
        display_short: "C48.1",
      },
      {
        key: "C48.2",
        en: "",
        de: "Malignant neoplasm: Peritoneum, unspecified",
        display_short: "C48.2",
      },
      {
        key: "C48.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of retroperitoneum and peritoneum",
        display_short: "C48.8",
      },
      {
        key: "C49",
        en: "",
        de: "Malignant neoplasm of other connective and soft tissue",
        display_short: "C49",
      },
      {
        key: "C49.0",
        en: "",
        de: "Malignant neoplasm: Connective and soft tissue of head, face and neck",
        display_short: "C49.0",
      },
      {
        key: "C49.1",
        en: "",
        de: "Malignant neoplasm: Connective and soft tissue of upper limb, including shoulder",
        display_short: "C49.1",
      },
      {
        key: "C49.2",
        en: "",
        de: "Malignant neoplasm: Connective and soft tissue of lower limb, including hip",
        display_short: "C49.2",
      },
      {
        key: "C49.3",
        en: "",
        de: "Malignant neoplasm: Connective and soft tissue of thorax",
        display_short: "C49.3",
      },
      {
        key: "C49.4",
        en: "",
        de: "Malignant neoplasm: Connective and soft tissue of abdomen",
        display_short: "C49.4",
      },
      {
        key: "C49.5",
        en: "",
        de: "Malignant neoplasm: Connective and soft tissue of pelvis",
        display_short: "C49.5",
      },
      {
        key: "C49.6",
        en: "",
        de: "Malignant neoplasm: Connective and soft tissue of trunk, unspecified",
        display_short: "C49.6",
      },
      {
        key: "C49.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of connective and soft tissue",
        display_short: "C49.8",
      },
      {
        key: "C49.9",
        en: "",
        de: "Malignant neoplasm: Connective and soft tissue, unspecified",
        display_short: "C49.9",
      },
      {
        key: "C50",
        en: "",
        de: "Malignant neoplasm of breast",
        display_short: "C50",
      },
      {
        key: "C50.0",
        en: "",
        de: "Malignant neoplasm: Nipple and areola",
        display_short: "C50.0",
      },
      {
        key: "C50.1",
        en: "",
        de: "Malignant neoplasm: Central portion of breast",
        display_short: "C50.1",
      },
      {
        key: "C50.2",
        en: "",
        de: "Malignant neoplasm: Upper-inner quadrant of breast",
        display_short: "C50.2",
      },
      {
        key: "C50.3",
        en: "",
        de: "Malignant neoplasm: Lower-inner quadrant of breast",
        display_short: "C50.3",
      },
      {
        key: "C50.4",
        en: "",
        de: "Malignant neoplasm: Upper-outer quadrant of breast",
        display_short: "C50.4",
      },
      {
        key: "C50.5",
        en: "",
        de: "Malignant neoplasm: Lower-outer quadrant of breast",
        display_short: "C50.5",
      },
      {
        key: "C50.6",
        en: "",
        de: "Malignant neoplasm: Axillary tail of breast",
        display_short: "C50.6",
      },
      {
        key: "C50.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of breast",
        display_short: "C50.8",
      },
      {
        key: "C50.9",
        en: "",
        de: "Malignant neoplasm: Breast, unspecified",
        display_short: "C50.9",
      },
      {
        key: "C51",
        en: "",
        de: "Malignant neoplasm of vulva",
        display_short: "C51",
      },
      {
        key: "C51.0",
        en: "",
        de: "Malignant neoplasm: Labium majus",
        display_short: "C51.0",
      },
      {
        key: "C51.1",
        en: "",
        de: "Malignant neoplasm: Labium minus",
        display_short: "C51.1",
      },
      {
        key: "C51.2",
        en: "",
        de: "Malignant neoplasm: Clitoris",
        display_short: "C51.2",
      },
      {
        key: "C51.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of vulva",
        display_short: "C51.8",
      },
      {
        key: "C51.9",
        en: "",
        de: "Malignant neoplasm: Vulva, unspecified",
        display_short: "C51.9",
      },
      {
        key: "C52",
        en: "",
        de: "Malignant neoplasm of vagina",
        display_short: "C52",
      },
      {
        key: "C53",
        en: "",
        de: "Malignant neoplasm of cervix uteri",
        display_short: "C53",
      },
      {
        key: "C53.0",
        en: "",
        de: "Malignant neoplasm: Endocervix",
        display_short: "C53.0",
      },
      {
        key: "C53.1",
        en: "",
        de: "Malignant neoplasm: Exocervix",
        display_short: "C53.1",
      },
      {
        key: "C53.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of cervix uteri",
        display_short: "C53.8",
      },
      {
        key: "C53.9",
        en: "",
        de: "Malignant neoplasm: Cervix uteri, unspecified",
        display_short: "C53.9",
      },
      {
        key: "C54",
        en: "",
        de: "Malignant neoplasm of corpus uteri",
        display_short: "C54",
      },
      {
        key: "C54.0",
        en: "",
        de: "Malignant neoplasm: Isthmus uteri",
        display_short: "C54.0",
      },
      {
        key: "C54.1",
        en: "",
        de: "Malignant neoplasm: Endometrium",
        display_short: "C54.1",
      },
      {
        key: "C54.2",
        en: "",
        de: "Malignant neoplasm: Myometrium",
        display_short: "C54.2",
      },
      {
        key: "C54.3",
        en: "",
        de: "Malignant neoplasm: Fundus uteri",
        display_short: "C54.3",
      },
      {
        key: "C54.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of corpus uteri",
        display_short: "C54.8",
      },
      {
        key: "C54.9",
        en: "",
        de: "Malignant neoplasm: Corpus uteri, unspecified",
        display_short: "C54.9",
      },
      {
        key: "C55",
        en: "",
        de: "Malignant neoplasm of uterus, part unspecified",
        display_short: "C55",
      },
      {
        key: "C56",
        en: "",
        de: "Malignant neoplasm of ovary",
        display_short: "C56",
      },
      {
        key: "C57",
        en: "",
        de: "Malignant neoplasm of other and unspecified female genital organs",
        display_short: "C57",
      },
      {
        key: "C57.0",
        en: "",
        de: "Malignant neoplasm: Fallopian tube",
        display_short: "C57.0",
      },
      {
        key: "C57.1",
        en: "",
        de: "Malignant neoplasm: Broad ligament",
        display_short: "C57.1",
      },
      {
        key: "C57.2",
        en: "",
        de: "Malignant neoplasm: Round ligament",
        display_short: "C57.2",
      },
      {
        key: "C57.3",
        en: "",
        de: "Malignant neoplasm: Parametrium",
        display_short: "C57.3",
      },
      {
        key: "C57.4",
        en: "",
        de: "Malignant neoplasm: Uterine adnexa, unspecified",
        display_short: "C57.4",
      },
      {
        key: "C57.7",
        en: "",
        de: "Malignant neoplasm: Other specified female genital organs",
        display_short: "C57.7",
      },
      {
        key: "C57.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of female genital organs",
        display_short: "C57.8",
      },
      {
        key: "C57.9",
        en: "",
        de: "Malignant neoplasm: Female genital organ, unspecified",
        display_short: "C57.9",
      },
      {
        key: "C58",
        en: "",
        de: "Malignant neoplasm of placenta",
        display_short: "C58",
      },
      {
        key: "C60",
        en: "",
        de: "Malignant neoplasm of penis",
        display_short: "C60",
      },
      {
        key: "C60.0",
        en: "",
        de: "Malignant neoplasm: Prepuce",
        display_short: "C60.0",
      },
      {
        key: "C60.1",
        en: "",
        de: "Malignant neoplasm: Glans penis",
        display_short: "C60.1",
      },
      {
        key: "C60.2",
        en: "",
        de: "Malignant neoplasm: Body of penis",
        display_short: "C60.2",
      },
      {
        key: "C60.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of penis",
        display_short: "C60.8",
      },
      {
        key: "C60.9",
        en: "",
        de: "Malignant neoplasm: Penis, unspecified",
        display_short: "C60.9",
      },
      {
        key: "C61",
        en: "",
        de: "Malignant neoplasm of prostate",
        display_short: "C61",
      },
      {
        key: "C62",
        en: "",
        de: "Malignant neoplasm of testis",
        display_short: "C62",
      },
      {
        key: "C62.0",
        en: "",
        de: "Malignant neoplasm: Undescended testis",
        display_short: "C62.0",
      },
      {
        key: "C62.1",
        en: "",
        de: "Malignant neoplasm: Descended testis",
        display_short: "C62.1",
      },
      {
        key: "C62.9",
        en: "",
        de: "Malignant neoplasm: Testis, unspecified",
        display_short: "C62.9",
      },
      {
        key: "C63",
        en: "",
        de: "Malignant neoplasm of other and unspecified male genital organs",
        display_short: "C63",
      },
      {
        key: "C63.0",
        en: "",
        de: "Malignant neoplasm: Epididymis",
        display_short: "C63.0",
      },
      {
        key: "C63.1",
        en: "",
        de: "Malignant neoplasm: Spermatic cord",
        display_short: "C63.1",
      },
      {
        key: "C63.2",
        en: "",
        de: "Malignant neoplasm: Scrotum",
        display_short: "C63.2",
      },
      {
        key: "C63.7",
        en: "",
        de: "Malignant neoplasm: Other specified male genital organs",
        display_short: "C63.7",
      },
      {
        key: "C63.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of male genital organs",
        display_short: "C63.8",
      },
      {
        key: "C63.9",
        en: "",
        de: "Malignant neoplasm: Male genital organ, unspecified",
        display_short: "C63.9",
      },
      {
        key: "C64",
        en: "",
        de: "Malignant neoplasm of kidney, except renal pelvis",
        display_short: "C64",
      },
      {
        key: "C65",
        en: "",
        de: "Malignant neoplasm of renal pelvis",
        display_short: "C65",
      },
      {
        key: "C66",
        en: "",
        de: "Malignant neoplasm of ureter",
        display_short: "C66",
      },
      {
        key: "C67",
        en: "",
        de: "Malignant neoplasm of bladder",
        display_short: "C67",
      },
      {
        key: "C67.0",
        en: "",
        de: "Malignant neoplasm: Trigone of bladder",
        display_short: "C67.0",
      },
      {
        key: "C67.1",
        en: "",
        de: "Malignant neoplasm: Dome of bladder",
        display_short: "C67.1",
      },
      {
        key: "C67.2",
        en: "",
        de: "Malignant neoplasm: Lateral wall of bladder",
        display_short: "C67.2",
      },
      {
        key: "C67.3",
        en: "",
        de: "Malignant neoplasm: Anterior wall of bladder",
        display_short: "C67.3",
      },
      {
        key: "C67.4",
        en: "",
        de: "Malignant neoplasm: Posterior wall of bladder",
        display_short: "C67.4",
      },
      {
        key: "C67.5",
        en: "",
        de: "Malignant neoplasm: Bladder neck",
        display_short: "C67.5",
      },
      {
        key: "C67.6",
        en: "",
        de: "Malignant neoplasm: Ureteric orifice",
        display_short: "C67.6",
      },
      {
        key: "C67.7",
        en: "",
        de: "Malignant neoplasm: Urachus",
        display_short: "C67.7",
      },
      {
        key: "C67.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of bladder",
        display_short: "C67.8",
      },
      {
        key: "C67.9",
        en: "",
        de: "Malignant neoplasm: Bladder, unspecified",
        display_short: "C67.9",
      },
      {
        key: "C68",
        en: "",
        de: "Malignant neoplasm of other and unspecified urinary organs",
        display_short: "C68",
      },
      {
        key: "C68.0",
        en: "",
        de: "Malignant neoplasm: Urethra",
        display_short: "C68.0",
      },
      {
        key: "C68.1",
        en: "",
        de: "Malignant neoplasm: Paraurethral gland",
        display_short: "C68.1",
      },
      {
        key: "C68.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of urinary organs",
        display_short: "C68.8",
      },
      {
        key: "C68.9",
        en: "",
        de: "Malignant neoplasm: Urinary organ, unspecified",
        display_short: "C68.9",
      },
      {
        key: "C69",
        en: "",
        de: "Malignant neoplasm of eye and adnexa",
        display_short: "C69",
      },
      {
        key: "C69.0",
        en: "",
        de: "Malignant neoplasm: Conjunctiva",
        display_short: "C69.0",
      },
      {
        key: "C69.1",
        en: "",
        de: "Malignant neoplasm: Cornea",
        display_short: "C69.1",
      },
      {
        key: "C69.2",
        en: "",
        de: "Malignant neoplasm: Retina",
        display_short: "C69.2",
      },
      {
        key: "C69.3",
        en: "",
        de: "Malignant neoplasm: Choroid",
        display_short: "C69.3",
      },
      {
        key: "C69.4",
        en: "",
        de: "Malignant neoplasm: Ciliary body",
        display_short: "C69.4",
      },
      {
        key: "C69.5",
        en: "",
        de: "Malignant neoplasm: Lacrimal gland and duct",
        display_short: "C69.5",
      },
      {
        key: "C69.6",
        en: "",
        de: "Malignant neoplasm: Orbit",
        display_short: "C69.6",
      },
      {
        key: "C69.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of eye and adnexa",
        display_short: "C69.8",
      },
      {
        key: "C69.9",
        en: "",
        de: "Malignant neoplasm: Eye, unspecified",
        display_short: "C69.9",
      },
      {
        key: "C70",
        en: "",
        de: "Malignant neoplasm of meninges",
        display_short: "C70",
      },
      {
        key: "C70.0",
        en: "",
        de: "Malignant neoplasm: Cerebral meninges",
        display_short: "C70.0",
      },
      {
        key: "C70.1",
        en: "",
        de: "Malignant neoplasm: Spinal meninges",
        display_short: "C70.1",
      },
      {
        key: "C70.9",
        en: "",
        de: "Malignant neoplasm: Meninges, unspecified",
        display_short: "C70.9",
      },
      {
        key: "C71",
        en: "",
        de: "Malignant neoplasm of brain",
        display_short: "C71",
      },
      {
        key: "C71.0",
        en: "",
        de: "Malignant neoplasm: Cerebrum, except lobes and ventricles",
        display_short: "C71.0",
      },
      {
        key: "C71.1",
        en: "",
        de: "Malignant neoplasm: Frontal lobe",
        display_short: "C71.1",
      },
      {
        key: "C71.2",
        en: "",
        de: "Malignant neoplasm: Temporal lobe",
        display_short: "C71.2",
      },
      {
        key: "C71.3",
        en: "",
        de: "Malignant neoplasm: Parietal lobe",
        display_short: "C71.3",
      },
      {
        key: "C71.4",
        en: "",
        de: "Malignant neoplasm: Occipital lobe",
        display_short: "C71.4",
      },
      {
        key: "C71.5",
        en: "",
        de: "Malignant neoplasm: Cerebral ventricle",
        display_short: "C71.5",
      },
      {
        key: "C71.6",
        en: "",
        de: "Malignant neoplasm: Cerebellum",
        display_short: "C71.6",
      },
      {
        key: "C71.7",
        en: "",
        de: "Malignant neoplasm: Brain stem",
        display_short: "C71.7",
      },
      {
        key: "C71.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of brain",
        display_short: "C71.8",
      },
      {
        key: "C71.9",
        en: "",
        de: "Malignant neoplasm: Brain, unspecified",
        display_short: "C71.9",
      },
      {
        key: "C72",
        en: "",
        de: "Malignant neoplasm of spinal cord, cranial nerves and other parts of central nervous system",
        display_short: "C72",
      },
      {
        key: "C72.0",
        en: "",
        de: "Malignant neoplasm: Spinal cord",
        display_short: "C72.0",
      },
      {
        key: "C72.1",
        en: "",
        de: "Malignant neoplasm: Cauda equina",
        display_short: "C72.1",
      },
      {
        key: "C72.2",
        en: "",
        de: "Malignant neoplasm: Olfactory nerve",
        display_short: "C72.2",
      },
      {
        key: "C72.3",
        en: "",
        de: "Malignant neoplasm: Optic nerve",
        display_short: "C72.3",
      },
      {
        key: "C72.4",
        en: "",
        de: "Malignant neoplasm: Acoustic nerve",
        display_short: "C72.4",
      },
      {
        key: "C72.5",
        en: "",
        de: "Malignant neoplasm: Other and unspecified cranial nerves",
        display_short: "C72.5",
      },
      {
        key: "C72.8",
        en: "",
        de: "Malignant neoplasm: Overlapping lesion of brain and other parts of central nervous system",
        display_short: "C72.8",
      },
      {
        key: "C72.9",
        en: "",
        de: "Malignant neoplasm: Central nervous system, unspecified",
        display_short: "C72.9",
      },
      {
        key: "C73",
        en: "",
        de: "Malignant neoplasm of thyroid gland",
        display_short: "C73",
      },
      {
        key: "C74",
        en: "",
        de: "Malignant neoplasm of adrenal gland",
        display_short: "C74",
      },
      {
        key: "C74.0",
        en: "",
        de: "Malignant neoplasm: Cortex of adrenal gland",
        display_short: "C74.0",
      },
      {
        key: "C74.1",
        en: "",
        de: "Malignant neoplasm: Medulla of adrenal gland",
        display_short: "C74.1",
      },
      {
        key: "C74.9",
        en: "",
        de: "Malignant neoplasm: Adrenal gland, unspecified",
        display_short: "C74.9",
      },
      {
        key: "C75",
        en: "",
        de: "Malignant neoplasm of other endocrine glands and related structures",
        display_short: "C75",
      },
      {
        key: "C75.0",
        en: "",
        de: "Malignant neoplasm: Parathyroid gland",
        display_short: "C75.0",
      },
      {
        key: "C75.1",
        en: "",
        de: "Malignant neoplasm: Pituitary gland",
        display_short: "C75.1",
      },
      {
        key: "C75.2",
        en: "",
        de: "Malignant neoplasm: Craniopharyngeal duct",
        display_short: "C75.2",
      },
      {
        key: "C75.3",
        en: "",
        de: "Malignant neoplasm: Pineal gland",
        display_short: "C75.3",
      },
      {
        key: "C75.4",
        en: "",
        de: "Malignant neoplasm: Carotid body",
        display_short: "C75.4",
      },
      {
        key: "C75.5",
        en: "",
        de: "Malignant neoplasm: Aortic body and other paraganglia",
        display_short: "C75.5",
      },
      {
        key: "C75.8",
        en: "",
        de: "Malignant neoplasm: Pluriglandular involvement, unspecified",
        display_short: "C75.8",
      },
      {
        key: "C75.9",
        en: "",
        de: "Malignant neoplasm: Endocrine gland, unspecified",
        display_short: "C75.9",
      },
      {
        key: "C76",
        en: "",
        de: "Malignant neoplasm of other and ill-defined sites",
        display_short: "C76",
      },
      {
        key: "C76.0",
        en: "",
        de: "Malignant neoplasm of other and ill-defined sites: Head, face and neck",
        display_short: "C76.0",
      },
      {
        key: "C76.1",
        en: "",
        de: "Malignant neoplasm of other and ill-defined sites: Thorax",
        display_short: "C76.1",
      },
      {
        key: "C76.2",
        en: "",
        de: "Malignant neoplasm of other and ill-defined sites: Abdomen",
        display_short: "C76.2",
      },
      {
        key: "C76.3",
        en: "",
        de: "Malignant neoplasm of other and ill-defined sites: Pelvis",
        display_short: "C76.3",
      },
      {
        key: "C76.4",
        en: "",
        de: "Malignant neoplasm of other and ill-defined sites: Upper limb",
        display_short: "C76.4",
      },
      {
        key: "C76.5",
        en: "",
        de: "Malignant neoplasm of other and ill-defined sites: Lower limb",
        display_short: "C76.5",
      },
      {
        key: "C76.7",
        en: "",
        de: "Malignant neoplasm of other and ill-defined sites: Other ill-defined sites",
        display_short: "C76.7",
      },
      {
        key: "C76.8",
        en: "",
        de: "Malignant neoplasm of other and ill-defined sites: Overlapping lesion of other and ill-defined sites",
        display_short: "C76.8",
      },
      {
        key: "C77",
        en: "",
        de: "Secondary and unspecified malignant neoplasm of lymph nodes",
        display_short: "C77",
      },
      {
        key: "C77.0",
        en: "",
        de: "Secondary and unspecified malignant neoplasm: Lymph nodes of head, face and neck",
        display_short: "C77.0",
      },
      {
        key: "C77.1",
        en: "",
        de: "Secondary and unspecified malignant neoplasm: Intrathoracic lymph nodes",
        display_short: "C77.1",
      },
      {
        key: "C77.2",
        en: "",
        de: "Secondary and unspecified malignant neoplasm: Intra-abdominal lymph nodes",
        display_short: "C77.2",
      },
      {
        key: "C77.3",
        en: "",
        de: "Secondary and unspecified malignant neoplasm: Axillary and upper limb lymph nodes",
        display_short: "C77.3",
      },
      {
        key: "C77.4",
        en: "",
        de: "Secondary and unspecified malignant neoplasm: Inguinal and lower limb lymph nodes",
        display_short: "C77.4",
      },
      {
        key: "C77.5",
        en: "",
        de: "Secondary and unspecified malignant neoplasm: Intrapelvic lymph nodes",
        display_short: "C77.5",
      },
      {
        key: "C77.8",
        en: "",
        de: "Secondary and unspecified malignant neoplasm: Lymph nodes of multiple regions",
        display_short: "C77.8",
      },
      {
        key: "C77.9",
        en: "",
        de: "Secondary and unspecified malignant neoplasm: Lymph node, unspecified",
        display_short: "C77.9",
      },
      {
        key: "C78",
        en: "",
        de: "Secondary malignant neoplasm of respiratory and digestive organs",
        display_short: "C78",
      },
      {
        key: "C78.0",
        en: "",
        de: "Secondary malignant neoplasm of lung",
        display_short: "C78.0",
      },
      {
        key: "C78.1",
        en: "",
        de: "Secondary malignant neoplasm of mediastinum",
        display_short: "C78.1",
      },
      {
        key: "C78.2",
        en: "",
        de: "Secondary malignant neoplasm of pleura",
        display_short: "C78.2",
      },
      {
        key: "C78.3",
        en: "",
        de: "Secondary malignant neoplasm of other and unspecified respiratory organs",
        display_short: "C78.3",
      },
      {
        key: "C78.4",
        en: "",
        de: "Secondary malignant neoplasm of small intestine",
        display_short: "C78.4",
      },
      {
        key: "C78.5",
        en: "",
        de: "Secondary malignant neoplasm of large intestine and rectum",
        display_short: "C78.5",
      },
      {
        key: "C78.6",
        en: "",
        de: "Secondary malignant neoplasm of retroperitoneum and peritoneum",
        display_short: "C78.6",
      },
      {
        key: "C78.7",
        en: "",
        de: "Secondary malignant neoplasm of liver and intrahepatic bile duct",
        display_short: "C78.7",
      },
      {
        key: "C78.8",
        en: "",
        de: "Secondary malignant neoplasm of other and unspecified digestive organs",
        display_short: "C78.8",
      },
      {
        key: "C79",
        en: "",
        de: "Secondary malignant neoplasm of other and unspecified sites",
        display_short: "C79",
      },
      {
        key: "C79.0",
        en: "",
        de: "Secondary malignant neoplasm of kidney and renal pelvis",
        display_short: "C79.0",
      },
      {
        key: "C79.1",
        en: "",
        de: "Secondary malignant neoplasm of bladder and other and unspecified urinary organs",
        display_short: "C79.1",
      },
      {
        key: "C79.2",
        en: "",
        de: "Secondary malignant neoplasm of skin",
        display_short: "C79.2",
      },
      {
        key: "C79.3",
        en: "",
        de: "Secondary malignant neoplasm of brain and cerebral meninges",
        display_short: "C79.3",
      },
      {
        key: "C79.4",
        en: "",
        de: "Secondary malignant neoplasm of other and unspecified parts of nervous system",
        display_short: "C79.4",
      },
      {
        key: "C79.5",
        en: "",
        de: "Secondary malignant neoplasm of bone and bone marrow",
        display_short: "C79.5",
      },
      {
        key: "C79.6",
        en: "",
        de: "Secondary malignant neoplasm of ovary",
        display_short: "C79.6",
      },
      {
        key: "C79.7",
        en: "",
        de: "Secondary malignant neoplasm of adrenal gland",
        display_short: "C79.7",
      },
      {
        key: "C79.8",
        en: "",
        de: "Secondary malignant neoplasm of other specified sites",
        display_short: "C79.8",
      },
      {
        key: "C79.9",
        en: "",
        de: "Secondary malignant neoplasm, unspecified site",
        display_short: "C79.9",
      },
      {
        key: "C80",
        en: "",
        de: "Malignant neoplasm, without specification of site",
        display_short: "C80",
      },
      {
        key: "C80.0",
        en: "",
        de: "Malignant neoplasm, primary site unknown, so stated",
        display_short: "C80.0",
      },
      {
        key: "C80.9",
        en: "",
        de: "Malignant neoplasm, primary site unspecified",
        display_short: "C80.9",
      },
      {
        key: "C81",
        en: "",
        de: "Hodgkin lymphoma",
        display_short: "C81",
      },
      {
        key: "C81.0",
        en: "",
        de: "Nodular lymphocyte predominant Hodgkin lymphoma",
        display_short: "C81.0",
      },
      {
        key: "C81.1",
        en: "",
        de: "Nodular sclerosis classical Hodgkin lymphoma",
        display_short: "C81.1",
      },
      {
        key: "C81.2",
        en: "",
        de: "Mixed cellularity classical Hodgkin lymphoma",
        display_short: "C81.2",
      },
      {
        key: "C81.3",
        en: "",
        de: "Lymphocyte depleted classical Hodgkin lymphoma",
        display_short: "C81.3",
      },
      {
        key: "C81.4",
        en: "",
        de: "Lymphocyte-rich (classical) Hodgkin lymphoma",
        display_short: "C81.4",
      },
      {
        key: "C81.7",
        en: "",
        de: "Other classical Hodgkin lymphoma",
        display_short: "C81.7",
      },
      {
        key: "C81.9",
        en: "",
        de: "Hodgkin lymphoma, unspecified",
        display_short: "C81.9",
      },
      {
        key: "C82",
        en: "",
        de: "Follicular lymphoma",
        display_short: "C82",
      },
      {
        key: "C82.0",
        en: "",
        de: "Follicular lymphoma grade I",
        display_short: "C82.0",
      },
      {
        key: "C82.1",
        en: "",
        de: "Follicular lymphoma grade II",
        display_short: "C82.1",
      },
      {
        key: "C82.2",
        en: "",
        de: "Follicular lymphoma grade III, unspecified",
        display_short: "C82.2",
      },
      {
        key: "C82.3",
        en: "",
        de: "Follicular lymphoma grade IIIa",
        display_short: "C82.3",
      },
      {
        key: "C82.4",
        en: "",
        de: "Follicular lymphoma grade IIIb",
        display_short: "C82.4",
      },
      {
        key: "C82.5",
        en: "",
        de: "Diffuse follicle centre lymphoma",
        display_short: "C82.5",
      },
      {
        key: "C82.6",
        en: "",
        de: "Cutaneous follicle centre lymphoma",
        display_short: "C82.6",
      },
      {
        key: "C82.7",
        en: "",
        de: "Other types of follicular lymphoma",
        display_short: "C82.7",
      },
      {
        key: "C82.9",
        en: "",
        de: "Follicular lymphoma, unspecified",
        display_short: "C82.9",
      },
      {
        key: "C83",
        en: "",
        de: "Non-follicular lymphoma",
        display_short: "C83",
      },
      {
        key: "C83.0",
        en: "",
        de: "Small cell B-cell lymphoma",
        display_short: "C83.0",
      },
      {
        key: "C83.1",
        en: "",
        de: "Mantle cell lymphoma",
        display_short: "C83.1",
      },
      {
        key: "C83.3",
        en: "",
        de: "Diffuse large B-cell lymphoma",
        display_short: "C83.3",
      },
      {
        key: "C83.5",
        en: "",
        de: "Lymphoblastic (diffuse) lymphoma",
        display_short: "C83.5",
      },
      {
        key: "C83.7",
        en: "",
        de: "Burkitt lymphoma",
        display_short: "C83.7",
      },
      {
        key: "C83.8",
        en: "",
        de: "Other non-follicular lymphoma",
        display_short: "C83.8",
      },
      {
        key: "C83.9",
        en: "",
        de: "Non-follicular (diffuse) lymphoma, unspecified",
        display_short: "C83.9",
      },
      {
        key: "C84",
        en: "",
        de: "Mature T/NK-cell lymphomas",
        display_short: "C84",
      },
      {
        key: "C84.0",
        en: "",
        de: "Mycosis fungoides",
        display_short: "C84.0",
      },
      {
        key: "C84.1",
        en: "",
        de: "Sézary disease",
        display_short: "C84.1",
      },
      {
        key: "C84.4",
        en: "",
        de: "Peripheral T-cell lymphoma, not elsewhere classified",
        display_short: "C84.4",
      },
      {
        key: "C84.5",
        en: "",
        de: "Other mature T/NK-cell lymphomas",
        display_short: "C84.5",
      },
      {
        key: "C84.6",
        en: "",
        de: "Anaplastic large cell lymphoma, ALK-positive",
        display_short: "C84.6",
      },
      {
        key: "C84.7",
        en: "",
        de: "Anaplastic large cell lymphoma, ALK-negative",
        display_short: "C84.7",
      },
      {
        key: "C84.8",
        en: "",
        de: "Cutaneous T-cell lymphoma, unspecified",
        display_short: "C84.8",
      },
      {
        key: "C84.9",
        en: "",
        de: "Mature T/NK-cell lymphoma, unspecified",
        display_short: "C84.9",
      },
      {
        key: "C85",
        en: "",
        de: "Other and unspecified types of non-Hodgkin lymphoma",
        display_short: "C85",
      },
      {
        key: "C85.1",
        en: "",
        de: "B-cell lymphoma, unspecified",
        display_short: "C85.1",
      },
      {
        key: "C85.2",
        en: "",
        de: "Mediastinal (thymic) large B-cell lymphoma",
        display_short: "C85.2",
      },
      {
        key: "C85.7",
        en: "",
        de: "Other specified types of non-Hodgkin lymphoma",
        display_short: "C85.7",
      },
      {
        key: "C85.9",
        en: "",
        de: "Non-Hodgkin lymphoma, unspecified",
        display_short: "C85.9",
      },
      {
        key: "C86",
        en: "",
        de: "Other specified types of T/NK-cell lymphoma",
        display_short: "C86",
      },
      {
        key: "C86.0",
        en: "",
        de: "Extranodal NK/T-cell lymphoma, nasal type",
        display_short: "C86.0",
      },
      {
        key: "C86.1",
        en: "",
        de: "Hepatosplenic T-cell lymphoma",
        display_short: "C86.1",
      },
      {
        key: "C86.2",
        en: "",
        de: "Enteropathy-type (intestinal) T-cell lymphoma",
        display_short: "C86.2",
      },
      {
        key: "C86.3",
        en: "",
        de: "Subcutaneous panniculitis-like T-cell lymphoma",
        display_short: "C86.3",
      },
      {
        key: "C86.4",
        en: "",
        de: "Blastic NK-cell lymphoma",
        display_short: "C86.4",
      },
      {
        key: "C86.5",
        en: "",
        de: "Angioimmunoblastic T-cell lymphoma",
        display_short: "C86.5",
      },
      {
        key: "C86.6",
        en: "",
        de: "Primary cutaneous CD30-positive T-cell proliferations",
        display_short: "C86.6",
      },
      {
        key: "C88",
        en: "",
        de: "Malignant immunoproliferative diseases",
        display_short: "C88",
      },
      {
        key: "C88.0",
        en: "",
        de: "Waldenström macroglobulinaemia",
        display_short: "C88.0",
      },
      {
        key: "C88.2",
        en: "",
        de: "Other heavy chain disease",
        display_short: "C88.2",
      },
      {
        key: "C88.3",
        en: "",
        de: "Immunoproliferative small intestinal disease",
        display_short: "C88.3",
      },
      {
        key: "C88.4",
        en: "",
        de: "Extranodal marginal zone B-cell lymphoma of mucosa-associated lymphoid tissue [MALT-lyphoma]",
        display_short: "C88.4",
      },
      {
        key: "C88.7",
        en: "",
        de: "Other malignant immunoproliferative diseases",
        display_short: "C88.7",
      },
      {
        key: "C88.9",
        en: "",
        de: "Malignant immunoproliferative disease, unspecified",
        display_short: "C88.9",
      },
      {
        key: "C90",
        en: "",
        de: "Multiple myeloma and malignant plasma cell neoplasms",
        display_short: "C90",
      },
      {
        key: "C90.0",
        en: "",
        de: "Multiple myeloma",
        display_short: "C90.0",
      },
      {
        key: "C90.1",
        en: "",
        de: "Plasma cell leukaemia",
        display_short: "C90.1",
      },
      {
        key: "C90.2",
        en: "",
        de: "Extramedullary plasmacytoma",
        display_short: "C90.2",
      },
      {
        key: "C90.3",
        en: "",
        de: "Solitary plasmacytoma",
        display_short: "C90.3",
      },
      {
        key: "C91",
        en: "",
        de: "Lymphoid leukaemia",
        display_short: "C91",
      },
      {
        key: "C91.0",
        en: "",
        de: "Acute lymphoblastic leukaemia [ALL]",
        display_short: "C91.0",
      },
      {
        key: "C91.1",
        en: "",
        de: "Chronic lymphocytic leukaemia of B-cell type",
        display_short: "C91.1",
      },
      {
        key: "C91.3",
        en: "",
        de: "Prolymphocytic leukaemia of B-cell type",
        display_short: "C91.3",
      },
      {
        key: "C91.4",
        en: "",
        de: "Hairy-cell leukaemia",
        display_short: "C91.4",
      },
      {
        key: "C91.5",
        en: "",
        de: "Adult T-cell lymphoma/leukaemia [HTLV-1-associated]",
        display_short: "C91.5",
      },
      {
        key: "C91.6",
        en: "",
        de: "Prolymphocytic leukaemia of T-cell type",
        display_short: "C91.6",
      },
      {
        key: "C91.7",
        en: "",
        de: "Other lymphoid leukaemia",
        display_short: "C91.7",
      },
      {
        key: "C91.8",
        en: "",
        de: "Mature B-cell leukaemia Burkitt-type",
        display_short: "C91.8",
      },
      {
        key: "C91.9",
        en: "",
        de: "Lymphoid leukaemia, unspecified",
        display_short: "C91.9",
      },
      {
        key: "C92",
        en: "",
        de: "Myeloid leukaemia",
        display_short: "C92",
      },
      {
        key: "C92.0",
        en: "",
        de: "Acute myeloblastic leukaemia [AML]",
        display_short: "C92.0",
      },
      {
        key: "C92.1",
        en: "",
        de: "Chronic myeloid leukaemia [CML], BCR/ABL-positive",
        display_short: "C92.1",
      },
      {
        key: "C92.2",
        en: "",
        de: "Atypical chronic myeloid leukaemia, BCR/ABL- negative",
        display_short: "C92.2",
      },
      {
        key: "C92.3",
        en: "",
        de: "Myeloid sarcoma",
        display_short: "C92.3",
      },
      {
        key: "C92.4",
        en: "",
        de: "Acute promyelocytic leukaemia [PML]",
        display_short: "C92.4",
      },
      {
        key: "C92.5",
        en: "",
        de: "Acute myelomonocytic leukaemia",
        display_short: "C92.5",
      },
      {
        key: "C92.6",
        en: "",
        de: "Acute myeloid leukaemia with 11q23-abnormality",
        display_short: "C92.6",
      },
      {
        key: "C92.7",
        en: "",
        de: "Other myeloid leukaemia",
        display_short: "C92.7",
      },
      {
        key: "C92.8",
        en: "",
        de: "Acute myeloid leukaemia with multilineage dysplasia",
        display_short: "C92.8",
      },
      {
        key: "C92.9",
        en: "",
        de: "Myeloid leukaemia, unspecified",
        display_short: "C92.9",
      },
      {
        key: "C93",
        en: "",
        de: "Monocytic leukaemia",
        display_short: "C93",
      },
      {
        key: "C93.0",
        en: "",
        de: "Acute monoblastic/monocytic leukaemia",
        display_short: "C93.0",
      },
      {
        key: "C93.1",
        en: "",
        de: "Chronic myelomonocytic leukaemia",
        display_short: "C93.1",
      },
      {
        key: "C93.3",
        en: "",
        de: "Juvenile myelomonocytic leukaemia",
        display_short: "C93.3",
      },
      {
        key: "C93.7",
        en: "",
        de: "Other monocytic leukaemia",
        display_short: "C93.7",
      },
      {
        key: "C93.9",
        en: "",
        de: "Monocytic leukaemia, unspecified",
        display_short: "C93.9",
      },
      {
        key: "C94",
        en: "",
        de: "Other leukaemias of specified cell type",
        display_short: "C94",
      },
      {
        key: "C94.0",
        en: "",
        de: "Acute erythroid leukaemia",
        display_short: "C94.0",
      },
      {
        key: "C94.2",
        en: "",
        de: "Acute megakaryoblastic leukaemia",
        display_short: "C94.2",
      },
      {
        key: "C94.3",
        en: "",
        de: "Mast cell leukaemia",
        display_short: "C94.3",
      },
      {
        key: "C94.4",
        en: "",
        de: "Acute panmyelosis with myelofibrosis",
        display_short: "C94.4",
      },
      {
        key: "C94.6",
        en: "",
        de: "Myelodysplastic and myeloproliferative disease, not elsewhere classified",
        display_short: "C94.6",
      },
      {
        key: "C94.7",
        en: "",
        de: "Other specified leukaemias",
        display_short: "C94.7",
      },
      {
        key: "C95",
        en: "",
        de: "Leukaemia of unspecified cell type",
        display_short: "C95",
      },
      {
        key: "C95.0",
        en: "",
        de: "Acute leukaemia of unspecified cell type",
        display_short: "C95.0",
      },
      {
        key: "C95.1",
        en: "",
        de: "Chronic leukaemia of unspecified cell type",
        display_short: "C95.1",
      },
      {
        key: "C95.7",
        en: "",
        de: "Other leukaemia of unspecified cell type",
        display_short: "C95.7",
      },
      {
        key: "C95.9",
        en: "",
        de: "Leukaemia, unspecified",
        display_short: "C95.9",
      },
      {
        key: "C96",
        en: "",
        de: "Other and unspecified malignant neoplasms of lymphoid, haematopoietic and related tissue",
        display_short: "C96",
      },
      {
        key: "C96.0",
        en: "",
        de: "Multifocal and multisystemic (disseminated) Langerhans-cell histiocytosis [Letterer-Siwe disease]",
        display_short: "C96.0",
      },
      {
        key: "C96.2",
        en: "",
        de: "Malignant mast cell tumour",
        display_short: "C96.2",
      },
      {
        key: "C96.4",
        en: "",
        de: "Sarcoma of dendritic cells (accessory cells)",
        display_short: "C96.4",
      },
      {
        key: "C96.5",
        en: "",
        de: "Multifocal and unisystemic Langerhans-cell histiocytosis",
        display_short: "C96.5",
      },
      {
        key: "C96.6",
        en: "",
        de: "Unifocal Langerhans-cell histiocytosis",
        display_short: "C96.6",
      },
      {
        key: "C96.7",
        en: "",
        de: "Other specified malignant neoplasms of lymphoid, haematopoietic and related tissue",
        display_short: "C96.7",
      },
      {
        key: "C96.8",
        en: "",
        de: "Histiocytic sarcoma",
        display_short: "C96.8",
      },
      {
        key: "C96.9",
        en: "",
        de: "Malignant neoplasm of lymphoid, haematopoietic and related tissue, unspecified",
        display_short: "C96.9",
      },
  ]
);
